In [2]:
import numpy as np

In [9]:
q_3 = np.array([1, 2, 3, 4])
q_3

array([1, 2, 3, 4])

In [10]:
q_4_ones = np.ones((3, 4))
q_4_zeros = np.zeros((4, 3))
q_4_ones
q_4_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
rng = np.random.default_rng()
q_5_A = rng.random((2,3))
q_5_B = rng.random((3,4))

np.matmul(q_5_A, q_5_B)

array([[0.46123049, 0.35710406, 1.03529742, 0.87987125],
       [0.34184662, 0.12292552, 0.59818853, 0.30742459]])

In [5]:
q_6 = np.array([[3,1], [1, 2]])
eigvals, eigvecs = np.linalg.eig(q_6)

print(eigvals)
print(eigvecs)

[3.61803399 1.38196601]
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
